// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR95rsqgyPSsEL2GpKMFMRj2ausOGjaZI',
    appId: '1:380797286545:web:4696ae11d24af77a25a730',
    messagingSenderId: '380797286545',
    projectId: 'ecommerce-946a0',
    authDomain: 'ecommerce-946a0.firebaseapp.com',
    storageBucket: 'ecommerce-946a0.appspot.com',
    measurementId: 'G-2S64W84LY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi0ypIgRyiLXnFe5S5OeZeIrz30p_FTdI',
    appId: '1:380797286545:android:c15e7319cc79bd9625a730',
    messagingSenderId: '380797286545',
    projectId: 'ecommerce-946a0',
    storageBucket: 'ecommerce-946a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcRhujEWwhS615nC3LBzSClfh2SJ9xvJU',
    appId: '1:380797286545:ios:963d1ff3545adb5225a730',
    messagingSenderId: '380797286545',
    projectId: 'ecommerce-946a0',
    storageBucket: 'ecommerce-946a0.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcRhujEWwhS615nC3LBzSClfh2SJ9xvJU',
    appId: '1:380797286545:ios:10887ddf88e2010625a730',
    messagingSenderId: '380797286545',
    projectId: 'ecommerce-946a0',
    storageBucket: 'ecommerce-946a0.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
